name: OpenSSF Scorecard

on:
  push:
  schedule:
    - cron: '23 3 * * *'  # daily at 03:23 UTC

permissions:
  contents: read

jobs:
  analysis:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Harden Runner
        uses: step-security/harden-runner@v2
        with:
          disable-sudo: true
          egress-policy: audit

      - name: Run OpenSSF Scorecard
        uses: ossf/scorecard-action@v2.4.2
        with:
          results_file: results.sarif
          results_format: sarif
          publish_results: true

      - name: Upload SARIF to code scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif

      - name: Upload Scorecard artifact
        uses: actions/upload-artifact@v4
        with:
          name: scorecard-results
          path: results.sarif
